# Generated by Django 3.2.9 on 2021-11-30 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_rename_records_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='filename',
            new_name='particulars',
        ),
    ]
