# Generated by Django 3.2.9 on 2021-11-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_rename_filename_record_particulars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='particulars',
            new_name='particulars_details',
        ),
    ]
