# Generated by Django 3.2.9 on 2021-11-30 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_rename_particulars_record_particulars_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='particulars_details',
            new_name='particulars',
        ),
    ]
